var lXdelta3 = require('../xdelta3');
var fs = require('fs');
var path = require('path');

var aSrcFd = fs.openSync(path.resolve(__dirname, 'files/txt1src'), 'r');
var aDstFd = fs.openSync(path.resolve(__dirname, 'files/txt1dst'), 'r');

var aDiffBufferList = [];

function getGoldenDiffForXdelta3_0_6() {
    // This will return a diff generated by Xdelta3 up to version 3.0.6
    return fs.readFileSync(path.resolve(__dirname, 'files/txt1gent.3.0.6'));
}

function getGoldenDiffForXdelta3_0_8() {
  // This will return a diff generated by Xdelta3 version 3.0.8+
  return fs.readFileSync(path.resolve(__dirname, 'files/txt1gent'));
}

var aDelta = new lXdelta3.DiffStream(aSrcFd, aDstFd);
aDelta.on('error', function(err) { throw err; });
aDelta.on('data', function(bufferChunk) {
  aDiffBufferList.push(bufferChunk);
});
aDelta.on('end', function() {
  var actualDiff = Buffer.concat(aDiffBufferList);
  fs.closeSync(aSrcFd);
  fs.closeSync(aDstFd);

  var expectedDiff = getGoldenDiffForXdelta3_0_6();
  if ( actualDiff.toString('hex') == expectedDiff.toString('hex') ) {
    console.log('OK:   Basic Diff');
  } else {
    expectedDiff = getGoldenDiffForXdelta3_0_8();
    if ( actualDiff.toString('hex') == expectedDiff.toString('hex') ) {
      console.log('OK:   Basic Diff');
    } else {
      console.log('FAIL: Basic Diff');  
    }
  }
});
