var lXdelta3 = require('../xdelta3');
var fs = require('fs');
var path = require('path');

// This will perform a test to verify the application of a patch using a patch generated by Xdelta3 version 3.0.8+
// Diffs generated by Xdelta 3.0.8+ are different then diffs generated by Xdelta 3.0.6 and older however they are
// backwards compatible. The below test should work with all versions of Xdelta. 

var aSrcFd = fs.openSync(path.resolve(__dirname, 'files/txt1src'), 'r');
var aDstFd = fs.openSync(path.resolve(__dirname, 'files/txt1result'), 'w');
var aPatch = new lXdelta3.PatchStream(aSrcFd, aDstFd);

aPatch.write(fs.readFileSync(path.resolve(__dirname, 'files/txt1gent')));
aPatch.end();
aPatch.on('close', function() {
  fs.closeSync(aSrcFd);
  fs.closeSync(aDstFd);
  if (fs.readFileSync(path.resolve(__dirname, 'files/txt1dst')).toString() == fs.readFileSync(path.resolve(__dirname, 'files/txt1result')).toString()) {
    console.log('OK:   Basic Patch');
  } else {
    console.log('FAIL: Basic Patch');
  }
});