/**
 * As of Xdelta3 version 3.0.8 (I think) the diffs are generated differently,
 * I belive to support larger files. Assuming your running Xdelta3 version 3.0.8+
 * then this test verifies that a diff generated by Xdelta3.0.6 can still be
 * applied when using a newer version of Xdelta.
 * 
 * If your using an older version of Xdetla (i.e. 3.0.6) then this test does 
 * exactly the same thing as test_patch_basic_1.js.
 */

var lXdelta3 = require('../xdelta3');
var fs = require('fs');
var path = require('path');

var aSrcFd = fs.openSync(path.resolve(__dirname, 'files/txt1src'), 'r');
var aDstFd = fs.openSync(path.resolve(__dirname, 'files/txt1result'), 'w');

var aPatch = new lXdelta3.PatchStream(aSrcFd, aDstFd);
aPatch.write(fs.readFileSync(path.resolve(__dirname, 'files/txt1gent.3.0.6')));
aPatch.end();
aPatch.on('close', function() {
  fs.closeSync(aSrcFd);
  fs.closeSync(aDstFd);
  if (fs.readFileSync(path.resolve(__dirname, 'files/txt1dst')).toString() == fs.readFileSync(path.resolve(__dirname, 'files/txt1result')).toString())
    console.log('OK:   Basic Patch Regression with diff from Xdelta 3.0.6');
  else
    console.log('FAIL: Basic Patch Regression with diff from Xdelta 3.0.6');
});

